version: '3.9'
services:
    apache:
        build: "./build/php"
        restart: always
        depends_on:
            - db
            - phpmyadmin
        volumes:
            - .:/var/www/html/
        ports:
            - "80:80"
    db:
        image: mysql
        restart: always
        build: "./build/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: adrespect
        ports:
            - "3308:3306"
        volumes:
            - dbData:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
volumes:
    app:
    dbData:
